//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUMUON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUMUON()
        {
            this.CHITIETMUONs = new HashSet<CHITIETMUON>();
        }
    
        public int MAPM { get; set; }
        public Nullable<int> MADG { get; set; }
        public Nullable<System.DateTime> NGAYMUON { get; set; }
        public Nullable<System.DateTime> NGAYTRA { get; set; }
        public Nullable<int> TONGSO_SACH { get; set; }
        public string TINHTRANG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETMUON> CHITIETMUONs { get; set; }
        public virtual DOCGIA DOCGIA { get; set; }
    }
}
